openapi: 3.0.1
info:
  title: '@jupiterone/graph-template'
  description: A template for JupiterOne graph converters.
  x-cortex-git:
    github:
      repository: JupiterOne/graph-template-deprecated
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-template'
  x-cortex-service-groups:
    - tier-4
